import { MazeData } from '../models/maze.models';

export const MOCK_MAZE: MazeData = {
  'start-cell': [6, 0],
  'end-cell': [0, 1],
  history: [
    { from: [6, 0], to: [6, 1] },
    { from: [6, 1], to: [5, 1] },
    { from: [5, 1], to: [5, 2] },
    { from: [5, 2], to: [5, 3] },
    { from: [5, 3], to: [5, 4] },
    { from: [5, 4], to: [6, 4] },
    { from: [6, 4], to: [6, 5] },
    { from: [6, 5], to: [5, 5] },
    { from: [5, 5], to: [4, 5] },
    { from: [4, 5], to: [4, 6] },
    { from: [4, 6], to: [3, 6] },
    { from: [3, 6], to: [3, 5] },
    { from: [3, 5], to: [2, 5] },
    { from: [2, 5], to: [1, 5] },
    { from: [1, 5], to: [1, 4] },
    { from: [1, 4], to: [2, 4] },
    { from: [2, 4], to: [3, 4] },
    { from: [3, 4], to: [3, 3] },
    { from: [3, 3], to: [2, 3] },
    { from: [2, 3], to: [1, 3] },
    { from: [1, 3], to: [1, 2] },
    { from: [1, 2], to: [1, 1] },
    { from: [1, 1], to: [1, 0] },
    { from: [1, 0], to: [2, 0] },
    { from: [2, 0], to: [3, 0] },
    { from: [3, 0], to: [4, 0] },
    { from: [4, 0], to: [4, 1] },
    { from: [4, 1], to: [3, 1] },
    { from: [3, 1], to: [2, 1] },
    { from: [2, 1], to: [2, 2] },
    { from: [2, 2], to: [3, 2] },
    { from: [3, 2], to: [4, 2] },
    { from: [4, 2], to: [4, 3] },
    { from: [4, 3], to: [4, 4] },
    { from: [4, 4], to: [4, 3] },
    { from: [4, 3], to: [4, 2] },
    { from: [4, 2], to: [3, 2] },
    { from: [3, 2], to: [2, 2] },
    { from: [2, 2], to: [2, 1] },
    { from: [2, 1], to: [3, 1] },
    { from: [3, 1], to: [4, 1] },
    { from: [4, 1], to: [4, 0] },
    { from: [4, 0], to: [5, 0] },
    { from: [5, 0], to: [4, 0] },
    { from: [4, 0], to: [3, 0] },
    { from: [3, 0], to: [2, 0] },
    { from: [2, 0], to: [1, 0] },
    { from: [1, 0], to: [0, 0] },
    { from: [0, 0], to: [0, 1] },
    { from: [0, 1], to: [0, 2] },
    { from: [0, 2], to: [0, 3] },
    { from: [0, 3], to: [0, 4] },
    { from: [0, 4], to: [0, 5] },
    { from: [0, 5], to: [0, 6] },
    { from: [0, 6], to: [1, 6] },
    { from: [1, 6], to: [2, 6] },
    { from: [2, 6], to: [1, 6] },
    { from: [1, 6], to: [0, 6] },
    { from: [0, 6], to: [0, 5] },
    { from: [0, 5], to: [0, 4] },
    { from: [0, 4], to: [0, 3] },
    { from: [0, 3], to: [0, 2] },
    { from: [0, 2], to: [0, 1] },
    { from: [0, 1], to: [0, 0] },
    { from: [0, 0], to: [1, 0] },
    { from: [1, 0], to: [1, 1] },
    { from: [1, 1], to: [1, 2] },
    { from: [1, 2], to: [1, 3] },
    { from: [1, 3], to: [2, 3] },
    { from: [2, 3], to: [3, 3] },
    { from: [3, 3], to: [3, 4] },
    { from: [3, 4], to: [2, 4] },
    { from: [2, 4], to: [1, 4] },
    { from: [1, 4], to: [1, 5] },
    { from: [1, 5], to: [2, 5] },
    { from: [2, 5], to: [3, 5] },
    { from: [3, 5], to: [3, 6] },
    { from: [3, 6], to: [4, 6] },
    { from: [4, 6], to: [5, 6] },
    { from: [5, 6], to: [6, 6] },
    { from: [6, 6], to: [5, 6] },
    { from: [5, 6], to: [4, 6] },
    { from: [4, 6], to: [4, 5] },
    { from: [4, 5], to: [5, 5] },
    { from: [5, 5], to: [6, 5] },
    { from: [6, 5], to: [6, 4] },
    { from: [6, 4], to: [6, 3] },
    { from: [6, 3], to: [6, 2] },
    { from: [6, 2], to: [6, 3] },
    { from: [6, 3], to: [6, 4] },
    { from: [6, 4], to: [5, 4] },
    { from: [5, 4], to: [5, 3] },
    { from: [5, 3], to: [5, 2] },
    { from: [5, 2], to: [5, 1] },
    { from: [5, 1], to: [6, 1] },
    { from: [6, 1], to: [6, 0] },
  ],
  grid: [
    [
      { 'visited?': true, walls: { n: true, e: false, s: false, w: true } },
      { 'visited?': true, walls: { n: false, e: false, s: true, w: false } },
      { 'visited?': true, walls: { n: true, e: false, s: true, w: false } },
      { 'visited?': true, walls: { n: true, e: false, s: true, w: false } },
      { 'visited?': true, walls: { n: true, e: false, s: true, w: false } },
      { 'visited?': true, walls: { n: true, e: false, s: true, w: false } },
      { 'visited?': true, walls: { n: true, e: true, s: false, w: false } },
    ],
    [
      { 'visited?': true, walls: { n: false, e: false, s: false, w: true } },
      { 'visited?': true, walls: { n: true, e: false, s: true, w: false } },
      { 'visited?': true, walls: { n: true, e: false, s: true, w: false } },
      { 'visited?': true, walls: { n: true, e: true, s: false, w: false } },
      { 'visited?': true, walls: { n: true, e: false, s: false, w: true } },
      { 'visited?': true, walls: { n: true, e: true, s: false, w: false } },
      { 'visited?': true, walls: { n: false, e: true, s: false, w: true } },
    ],
    [
      { 'visited?': true, walls: { n: false, e: true, s: false, w: true } },
      { 'visited?': true, walls: { n: true, e: false, s: false, w: true } },
      { 'visited?': true, walls: { n: true, e: true, s: false, w: false } },
      { 'visited?': true, walls: { n: false, e: true, s: false, w: true } },
      { 'visited?': true, walls: { n: false, e: true, s: false, w: true } },
      { 'visited?': true, walls: { n: false, e: true, s: false, w: true } },
      { 'visited?': true, walls: { n: false, e: true, s: true, w: true } },
    ],
    [
      { 'visited?': true, walls: { n: false, e: true, s: false, w: true } },
      { 'visited?': true, walls: { n: false, e: true, s: false, w: true } },
      { 'visited?': true, walls: { n: false, e: true, s: false, w: true } },
      { 'visited?': true, walls: { n: false, e: false, s: true, w: true } },
      { 'visited?': true, walls: { n: false, e: true, s: true, w: false } },
      { 'visited?': true, walls: { n: false, e: false, s: true, w: true } },
      { 'visited?': true, walls: { n: true, e: true, s: false, w: false } },
    ],
    [
      { 'visited?': true, walls: { n: false, e: false, s: false, w: true } },
      { 'visited?': true, walls: { n: false, e: true, s: true, w: false } },
      { 'visited?': true, walls: { n: false, e: false, s: true, w: true } },
      { 'visited?': true, walls: { n: true, e: false, s: true, w: false } },
      { 'visited?': true, walls: { n: true, e: true, s: true, w: false } },
      { 'visited?': true, walls: { n: true, e: false, s: false, w: true } },
      { 'visited?': true, walls: { n: false, e: true, s: false, w: false } },
    ],
    [
      { 'visited?': true, walls: { n: false, e: true, s: true, w: true } },
      { 'visited?': true, walls: { n: true, e: false, s: false, w: true } },
      { 'visited?': true, walls: { n: true, e: false, s: true, w: false } },
      { 'visited?': true, walls: { n: true, e: false, s: true, w: false } },
      { 'visited?': true, walls: { n: true, e: true, s: false, w: false } },
      { 'visited?': true, walls: { n: false, e: true, s: false, w: true } },
      { 'visited?': true, walls: { n: false, e: true, s: false, w: true } },
    ],
    [
      { 'visited?': true, walls: { n: true, e: false, s: false, w: true } },
      { 'visited?': true, walls: { n: false, e: true, s: true, w: false } },
      { 'visited?': true, walls: { n: true, e: false, s: true, w: true } },
      { 'visited?': true, walls: { n: true, e: false, s: true, w: false } },
      { 'visited?': true, walls: { n: false, e: false, s: true, w: false } },
      { 'visited?': true, walls: { n: false, e: true, s: true, w: false } },
      { 'visited?': true, walls: { n: false, e: true, s: true, w: true } },
    ],
  ],
};
